language: python

python:
  - "2.7"
  - "3.4"

install: python setup.py -q install
before_script: pip install -r requirements-test.txt
script: coverage run --source dadosgovbr setup.py test
after_success: coveralls
